apiVersion: v1
kind: Secret
metadata:
  name: {{ template "broker.secret" . }}
  labels:
    app: {{ template "mariadb-nodejs-broker.name" . }}
    chart: {{ template "mariadb-nodejs-broker.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  username: "{{ .Values.broker.username | b64enc }}"
  password: "{{ .Values.broker.password | b64enc }}"