apiVersion: servicecatalog.k8s.io/v1beta1
kind: ClusterServiceBroker
metadata:
  name: {{ template "broker.name" . }}
  labels:
    app: {{ template "mariadb-nodejs-broker.name" . }}
    chart: {{ template "mariadb-nodejs-broker.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  url: "http://{{ template "broker.url" . }}:{{ .Values.service.port }}"
  authInfo:
    basic:
      secretRef:
        namespace: {{ .Release.Namespace }}
        name: {{ template "broker.secret" . }}