apiVersion: v1
kind: Service
metadata:
  name: {{ template "broker.service" . }}
  labels:
    app: {{ template "mariadb-nodejs-broker.name" . }}
    chart: {{ template "mariadb-nodejs-broker.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  {{- if eq .Values.service.type "NodePort" }}
  {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
  {{- end }}
  {{- end }}
  selector:
    app: {{ template "mariadb-nodejs-broker.name" . }}
    release: {{ .Release.Name }}
